### ISSUE TITLE
airswap account:import   Met error

### ISSUE THREAD

**Issue by clarkchen** [airswap/airswap-cli#117]
system:	Ubuntu 22.04.2 LTS
node: 16.20
yarn: 1.22.19
airswap: 4.1.0

-----

when call `airswap account:import `

met error
```
Error Cannot import account because dependencies are missing.
If you are on Linux, try installing libsecret-1-dev (Debian, Ubuntu etc.) or libsecret-devel (RedHat, Fedora etc.) and then reinstalling AirSwap CLI.
```

![image](https://github.com/airswap/airswap-cli/assets/1352085/09ef964a-5ff3-4022-a226-5f877fb6a28e)

-----
and after install libsecret-1-dev 

```
sudo apt install   libsecret-1-dev 
```
still the same error

![image](https://github.com/airswap/airswap-cli/assets/1352085/f45d70ef-7bf1-400f-9dee-bcb5dfe05367)

**Comment by MMrj9** [comment]
Also having the same issue.

On my Ubuntu 23 Desktop it works fine. 

On VMs I tried both Ubuntu 22 and Ubuntu 23 and I get this error. Tried everything and wasn't able to fix it.

So I guess theres something on Ubuntu Desktop version that allows it to work.

**Comment by dmosites** [comment]
Thanks @clarkchen @MMrj9 we'll take a look shortly.
