### ISSUE TITLE
New command to support light order requests

### ISSUE THREAD

**Issue by dmosites** [airswap/airswap-cli#78]
The "light" protocol is a version of Swap that implements a minimal features to save on gas.

For clients to request a light order, there is a `swapContract` parameter sent in the request.
https://docs.airswap.io/system/apis#orders

If that `swapContract` is set to a light address, the server responds with a light order.
The latest light deployments for Rinkeby and Mainnet here:
https://docs.airswap.io/contract-deployments

For the most part, a `light` command would look very similar to the `order` command.
https://github.com/airswap/airswap-cli/tree/master/src/commands/order

**Comment by Xuefeng-Zhu** [comment]
@dmosites  Hi, I am interesting in working on this bounty. Will it be better that we add a option in prompt of order command instead of creating a new command

**Comment by dmosites** [comment]
Apologies for the delay @Xuefeng-Zhu. I could imagine it going either way, whether a dedicated `light` command or, for example, if the `order` command had a prompt for "full or light". What do you think now that you've had a look at it?

**Comment by Xuefeng-Zhu** [comment]
I think it will may be better add prompt, since essentially it is still order command, but with a flag

**Comment by Xuefeng-Zhu** [comment]
But current the main issue I had is that I cannot get a sample response from the command, for example
![image](https://user-images.githubusercontent.com/5875315/107691650-922cc580-6c60-11eb-8074-a32e8a7313ee.png)

**Comment by Xuefeng-Zhu** [comment]
One more question, where can I get the light protocol address? Are user supposed to enter it?

**Comment by dmosites** [comment]
You can add `@airswap/light` as a dependency and import `deploys.json` which is keyed by chain ID.

https://github.com/airswap/airswap-protocols/blob/master/source/light/deploys.json

**Comment by Xuefeng-Zhu** [comment]
@dmosites Cool. I have opened a PR to add this support https://github.com/airswap/airswap-cli/pull/79
