### ISSUE TITLE
v1.7.0 commands result in libsecret shared object missing file error

### ISSUE THREAD

**Issue by Ziinc** [airswap/airswap-cli#86]
Errors occured
```bash
root@fd3a80fb4415:/home# npx airswap debug
AirSwap CLI 1.7.0 — https://www.airswap.io/
    Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
root@fd3a80fb4415:/home# npx airswap chain
AirSwap CLI 1.7.0 — https://www.airswap.io/
    Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
root@fd3a80fb4415:/home# npx airswap quote:stream
AirSwap CLI 1.7.0 — https://www.airswap.io/
    Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
```

This occurs for both node 10 and node 14. Version shown for `npx airswap help`  in save env as above commands:
```
VERSION
  airswap/1.7.0 linux-x64 node-v14.17.5
```

Can be replicated using docker image `node:14` and `node:10`:
```bash
docker run -it node:14 bash

cd /home && npm init -y && npm i airswap

# all commands thereafter attempting to invoke airswap commands raises errors
npx airswap debug
```

**Comment by dmosites** [comment]
Hi @Ziinc this appears to be a similar issue: https://github.com/livepeer/livepeerjs/issues/380
We'll likely be able to make it an optional dependency, where you'd provide a private key for each command. In the meantime, installing `libsecret-1-dev` (Debian, Ubuntu etc.) or `libsecret-devel` (RedHat, Fedora etc.) should do the trick.
An updated version `1.7.1` was just published to handle this more gracefully.

**Comment by Ziinc** [comment]
Thanks, it works now. 

On a separate note, seems like this command is not working:
```
root@f83e3a9139ce:~# npx airswap indexer:get
AirSwap CLI 1.7.1 — https://www.airswap.io/
 ›   Error: command indexer:get not found
```
